DjangoBlogProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import blog

urlpatterns = [
       path('admin/', admin.site.urls),
       path('', include('blog.urls')),
       path('user/',include('users.urls'))
]

if settings.DEBUG:
       urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import about, PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, \
       PostLikeView, CommentView, CommentDeleteView, CommentUpdateView, FollowingUserListView, CommentReplyView

urlpatterns = [
       path('',PostListView.as_view() , name="blog-home"),
       path('about', about, name="blog-about" ),
       path('post/<int:pk>/',PostDetailView.as_view() , name="blog-detail"),
       path('post/create', PostCreateView.as_view() , name="blog-create"),
       path('post/<int:pk>/update',PostUpdateView.as_view() , name="blog-update"),
       path('post/<int:pk>/delete',PostDeleteView.as_view() , name="blog-delete"),
       path('post/<int:pk>/like',PostLikeView.as_view(),  name='blog-like'),
       path("post/<int:pk>/comment", CommentView.as_view(), name='blog-comment'),
       path("post/comment/<int:pk>/reply", CommentReplyView.as_view(), name='comment-reply'),
       path("post/comment/<int:pk>/delete", CommentDeleteView.as_view(), name='blog-comment-delete'),
       path("post/comment/<int:pk>/update", CommentUpdateView.as_view(), name='blog-comment-update'),

       path("following-feed", FollowingUserListView.as_view(), name="following-feed")
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class TimeStampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(blank=True, null=True)

    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name='%(class)s_created_by'  # dynamic: will be like 'comment_created_by'
    )
    updated_by = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name='%(class)s_updated_by',
        blank=True, null=True
    )

    class Meta:
        abstract = True

class Post(TimeStampedModel):
    title = models.CharField(max_length=100, blank=True, null=True)
    content = models.TextField()
    is_active = models.BooleanField(default=True)
    is_published = models.BooleanField(default=False)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('user-profile')

    def get_like_count(self):
        return self.like_set.count()

    def get_comment_count(self):
        return self.comment_set.count()

    def get_all_comments(self):
        return self.comment_set.all()

    def get_queryset(self):
        return Post.objects.filter(user_id=self.user_id).order_by('-created_at').all()

class Media(models.Model):
    file = models.FileField(upload_to="blog_media/", blank=True, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    @property
    def file_url(self):
        if self.file:
            return self.file.url
        return None

class Like(TimeStampedModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liked_by')

class Comment(TimeStampedModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField(blank=False, null=False)
    commented_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')

    def get_all_replies(self):
        return self.reply_set.all()

class Reply(TimeStampedModel):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    reply = models.TextField(blank=False, null=False)
    replied_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='replied_by')

blog/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.defaulttags import comment
from django.template.loader import render_to_string
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from blog.form import MediaForm, CommentForm, ReplyForm
from blog.models import Post, Media, Like, Comment, Reply
from users.models import Following


class PostListView(LoginRequiredMixin, ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'blog/home.html'
    ordering = ['-created_at']
    paginate_by = 3

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        user_likes =  Like.objects.filter(user = self.request.user).values_list('post_id', flat=True)
        context['liked_posts'] = user_likes

        context["following_users"] = (Following.objects.filter(follower_user=self.request.user).
                                      values_list('following_user_id',flat=True))

        context["login_user"] = self.request.user
        # breakpoint()
        if self.request.POST:
            context['comment_form'] = CommentForm(self.request.POST)
        else:
            context['comment_form'] = CommentForm()

        return context


class FollowingUserListView(LoginRequiredMixin, ListView):
    model = Post
    context_object_name = 'posts'
    template_name = "blog/home.html"
    paginate_by = 3

    def get_queryset(self):
        following_users = Following.objects.filter(
            follower_user=self.request.user
        ).values_list('following_user', flat=True)

        posts = Post.objects.filter(user_id__in=following_users).order_by('-created_at')
        return posts

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["login_user"] = self.request.user

        user_likes = Like.objects.filter(user=self.request.user).values_list('post_id', flat=True)
        context['liked_posts'] = user_likes

        context["following_users"] = Following.objects.filter(
            follower_user=self.request.user
        ).values_list('following_user', flat=True)

        # Comment form
        if self.request.POST:
            context['comment_form'] = CommentForm(self.request.POST)
        else:
            context['comment_form'] = CommentForm()
        return context

class PostDetailView(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_likes = Like.objects.filter(user=self.request.user).values_list('post_id', flat=True)
        context['liked_posts'] = user_likes

        post = self.get_object()
        if self.request.POST:
            context['comment_form'] = CommentForm(self.request.POST)
            context["reply_form"] = ReplyForm(self.request.POST)
        else:
            context['comment_form'] = CommentForm()
            context["reply_form"] = ReplyForm(self.request.POST)

        return context

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = "blog/post_form.html"
    fields = ['title', 'content']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.POST:
            context['media_form'] = MediaForm(self.request.POST, self.request.FILES)
        else:
            context['media_form'] = MediaForm()

        return context

    def form_valid(self, form):
        form.instance.user_id = self.request.user
        form.instance.created_by = self.request.user

        response = super().form_valid(form)

        # Handle media form
        media_files = self.request.FILES.getlist('file')
        if media_files:
            for f in media_files:
                Media.objects.create(post=self.object, file=f)

        return response


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = "blog/post_form.html"
    fields = ['title', 'content']

    def test_func(self):
        post = self.get_object()

        if self.request.user != post.user_id:
            return False
        return True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.POST:
            context['media_form'] = MediaForm(self.request.POST, self.request.FILES)
        else:
            context['media_form'] = MediaForm()

        return context

    def form_valid(self, form):
        form.instance.user_id = self.request.user
        form.instance.created_by = self.request.user

        response = super().form_valid(form)

        # Handle media form
        media_files = self.request.FILES.getlist('file')
        if media_files:
            for f in media_files:
                Media.objects.create(post=self.object, file=f)

        return response

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()

        if self.request.user != post.user_id:
            return False
        return True

class PostLikeView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, id=kwargs["pk"])
        liked = Like.objects.filter(user=request.user, post=post).first()

        if liked:
            liked.delete() # unlike the post if instance exists in database
            is_liked = False
        else:
            like = Like(user=request.user, post=post, created_by=request.user)
            like.save()
            is_liked = True

        # Send the update button
        html = render_to_string("partials/like_button.html",
                                {
                                    "post": post,
                                    "is_liked": is_liked,
                                },request=request)

        return HttpResponse(html)
        # return JsonResponse({
        #     'is_liked': is_liked,
        #     "likes": post.like_set.count(),
        # })


class CommentView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, id=kwargs["pk"])
        comment_text = request.POST.get('comment')

        if comment_text:
            comment = Comment(post=post, comment=comment_text, commented_by=request.user, created_by=request.user)
            comment.save()

        html = render_to_string("partials/comment_button.html",
                                {
                                    "post": post,
                                    "comment_form": CommentForm(),
                                }, request=request)

        return HttpResponse(html)

class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    success_url = "/"

    def test_func(self):
        comment = self.get_object()
        if self.request.user != comment.commented_by and self.request.user != comment.post.user_id:
            return False
        return True

class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    success_url = "user-profile"
    fields = ['comment']

    def test_func(self):
        comment = self.get_object()
        if self.request.user != comment.commented_by and self.request.user != comment.post.user_id:
            return False
        return True

    def post(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, id=kwargs["pk"])
        comment_text = request.POST.get('comment')
        if comment_text:
            comment.comment = comment_text
            comment.save()
            messages.success(request, f'Comment updated successfully!')

        return redirect('blog-detail', pk=comment.post.id)


class CommentReplyView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, id=kwargs["pk"])
        reply_text = request.POST.get('reply')

        if reply_text:
            reply = Reply(comment=comment, reply=reply_text,
                          replied_by=request.user, created_by=request.user)
            reply.save()
            messages.success(request, f'Replied successfully!')

        html = render_to_string("partials/reply_button.html",
                                {
                                    "comment": comment,
                                    "reply_form": ReplyForm(),
                                }, request=request)

        return HttpResponse(html)

def about(request):
    return render(request, 'blog/about.html', {"title": "About"})

blog/templates/blog/_left_sidebar.html
<div class="p-3 d-flex flex-column justify-content-between h-100">
    <div>
        <h4><a href="{% url 'blog-home' %}" class="text-light font-weight-bold">TwitterX</a></h4>

        <ul class="nav flex-column mt-4">
            <li class="nav-item sidebar-link p-2">
                <a class="nav-link text-light" href="{% url 'blog-home' %}">
                    <i class="bi bi-house-door-fill mr-2"></i> Home
                </a>
            </li>
            <li class="nav-item sidebar-link p-2">
                <a class="nav-link text-light" href="{% url 'blog-about' %}">
                    <i class="bi bi-info-circle-fill mr-2"></i> About
                </a>
            </li>
            <li class="nav-item sidebar-link p-2">
                <a class="nav-link text-light" href="#">
                    <i class="bi bi-hash mr-2"></i> Explore
                </a>
            </li>
            <li class="nav-item sidebar-link p-2">
                <a class="nav-link text-light" href="#">
                    <i class="bi bi-envelope-fill mr-2"></i> Messages
                </a>
            </li>
            <li class="nav-item sidebar-link p-2">
                <a class="nav-link text-light" href="{% url 'blog-create' %}">
                    <i class="bi bi-pencil-square mr-2"></i> Create post
                </a>
            </li>
            <li class="nav-item sidebar-link p-2">
                <a class="nav-link text-light" href="{% url "user-profile" %}">
                    <i class="bi bi-person-fill mr-2"></i> Profile
                </a>
            </li>
        </ul>

        <button class="btn btn-light text-dark btn-block mt-4 rounded-pill font-weight-bold" style="font-size: 1rem;">
            Post
        </button>
    </div>

    {% if user.is_authenticated %}
        <div class="dropdown mt-4">
            <a class="d-flex align-items-center text-decoration-none dropdown-toggle text-light" href="#"
               id="dropdownUser" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
               style="font-size: 1rem;">
                <img src="{{ user.profile.image.url|default:'media/profile_pics/default.jpg' }}"
                     width="40" height="40" class="rounded-circle mr-2" alt="profile image">
                <strong>@{{ user.username }}</strong>
            </a>
            <div class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownUser">
                <a class="dropdown-item" href="{% url 'password_change' %}">
                    <i class="bi bi-pencil-square mr-2"></i> Update Password
                </a>
                <form action="{% url 'user-logout' %}" method="post" class="m-0 p-0">
                    {% csrf_token %}
                    <button type="submit" class="dropdown-item text-dark d-flex align-items-center"
                            style="background: none; border: none; font-size: 1rem;">
                        <i class="bi bi-box-arrow-right mr-2"></i> Logout
                    </button>
                </form>
            </div>
        </div>
    {% else %}
        <div class="mt-4">
            <a href="{% url 'user-login' %}" class="btn btn-outline-light btn-block rounded-pill mb-2"
               style="font-size: 1rem;">Login</a>
            <a href="{% url 'user-register' %}" class="btn btn-primary btn-block rounded-pill" style="font-size: 1rem;">Sign
                Up</a>
        </div>
    {% endif %}
</div>

blog/templates/blog/_right_sidebar.html
<div class="right-sidebar">
    <h5 class="text-light">Who to follow</h5>
    <div class="d-flex justify-content-between align-items-center mb-2">
        <div><strong>@johndoe</strong><br><small class="text-muted">John Doe</small></div>
        <button class="btn btn-outline-primary btn-sm">Follow</button>
    </div>
    <div class="d-flex justify-content-between align-items-center mb-2">
        <div><strong>@techgirl</strong><br><small class="text-muted">Techie Girl</small></div>
        <button class="btn btn-outline-primary btn-sm">Follow</button>
    </div>
    <hr class="bg-secondary">
    <h6 class="text-light">Trending</h6>
    <p>#DjangoDark</p>
    <p>#Bootstrap</p>
    <p>#WebDev</p>
</div>

blog/templates/blog/about.html
{%  extends 'blog/base.html' %}
{% block content %}
    <div style="align-content: center">
            <h3> Hey there it is about page !</h3>
    </div>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% if title %}Blog - {{ title }}{% else %}Blog App{% endif %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
</head>
<body>
<div class="container-fluid">
    <div class="row">

        <!-- Left Sidebar -->
        <div class="sidebar text-light p-3"
             style="position: fixed; top: 0; left: 0; height: 100vh; width: 300px; overflow: hidden;">
            {% include 'blog/_left_sidebar.html' %}
        </div>

        <!-- Main Feed -->
        <div class="content-area col-md-6 min-vh-100" style="margin-left: 350px;">
            <div class="container mt-2">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible fade show custom-flash"
                             role="alert">
                            {{ message }}
                            <button type="button" class="close text-black" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            {% block content %}{% endblock %}
        </div>

        <!-- Right Sidebar -->
        <div class="col-md-3 d-none d-md-block p-3">
            {% include 'blog/_right_sidebar.html' %}
        </div>

    </div>
</div>

<!-- Scripts -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"></script>
<script src="https://unpkg.com/htmx.org@2.0.4"
            integrity="sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+"
            crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'blog/main.js' %}?v=1.2"></script>
</body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_filters %}
{% block content %}


    <div class="card bg-dark text-light mb-4 shadow-sm border-0 rounded">
        <div class="card-body">
            <!-- Profile Info -->
            <div class="d-flex align-items-center mb-2">
                <!-- Profile Image -->
                <img src="{{ object.user_id.profile.image.url|default:'https://via.placeholder.com/50?text=U' }}"
                     alt="Profile"
                     class="rounded-circle mr-3 border border-secondary"
                     width="50" height="50">

                <!-- User Info + Date + 3-dot menu -->
                <div class="w-100">
                    <div class="d-flex justify-content-between align-items-center">
                        <!-- Name & Username -->
                        <div>
                            <strong>{{ object.user_id.first_name }} {{ object.user_id.last_name }}</strong>
                            <span class="text-muted ml-1">@{{ object.user_id.username }}</span>
                        </div>

                        <!-- Date + Dropdown -->
                        <div class="d-flex align-items-center">
                            <small class="text-muted mr-2">{{ object.created_at|date:"M d, Y" }}</small>

                            {% if object.user_id == user %}
                                <!-- 3 Dot Dropdown -->
                                <div class="dropdown">
                                    <button class="btn btn-sm text-light p-0 border-0 bg-transparent" type="button"
                                            id="postDropdown{{ object.id }}"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="bi bi-three-dots-vertical" style="font-size: 1.2rem;"></i>
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right bg-dark text-light shadow-sm"
                                         aria-labelledby="postDropdown{{ object.id }}">
                                        <a class="dropdown-item text-light" href="{% url 'blog-update' object.id %}">
                                            <i class="bi bi-pencil-square mr-2"></i> Update Post
                                        </a>
                                        <form method="POST" action="{% url 'blog-delete' object.id %}" class="m-0 p-0">
                                            {% csrf_token %}
                                            <button type="submit" class="dropdown-item text-light"
                                                    style="background: none; border: none;">
                                                <i class="bi bi-trash mr-2"></i> Delete Post
                                            </button>
                                        </form>
                                    </div>
                                </div>

                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>


            <!-- Post Content -->
            <div class="mt-3 mb-3" style="font-size: 1.2rem;">
                <a href="{% url 'blog-detail' object.id %}" class="text-light text-decoration-none">
                    {{ object.content }}
                </a>
            </div>

            <!-- Media (centered, no bottom border) -->
            {% if object.media_set.all %}
                <!-- Bootstrap Carousel -->
                <div id="carouselPost{{ object.id }}" class="carousel slide mb-3" data-ride="carousel">
                    <div class="carousel-inner rounded overflow-hidden">
                        {% for media in object.media_set.all %}
                            <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                <img src="{{ media.file_url|default_if_none:'#' }}"
                                     class="d-block w-100"
                                     style="max-height: 400px; object-fit: cover; cursor: zoom-in;"
                                     data-toggle="modal"
                                     data-target="#imageModal{{ object.id }}{{ forloop.counter }}">
                            </div>
                        {% endfor %}
                    </div>

                    {% if object.media_set.all|length > 1 %}
                        <a class="carousel-control-prev" href="#carouselPost{{ object.id }}" role="button"
                           data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselPost{{ object.id }}" role="button"
                           data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    {% endif %}
                </div>

                <!-- Image Modals -->
                {% for media in object.media_set.all %}
                    <div class="modal fade" id="imageModal{{ object.id }}{{ forloop.counter }}" tabindex="-1"
                         role="dialog" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                            <div class="modal-content bg-dark border-0">
                                <div class="modal-body p-0">
                                    <img src="{{ media.file_url|default_if_none:'#' }}"
                                         class="img-fluid w-100"
                                         style="object-fit: contain;">
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}

            <!-- Buttons: No border, cleaner spacing -->
            <div class="d-flex justify-content-around mt-3">
                <div id="like-button-{{ post.id }}" hx-swap="outerHTML">
                    {% if post.id in liked_posts %}
                        {% include "partials/like_button.html" with post=post is_liked=True  total_likes=total_likes %}
                    {% else %}
                        {% include "partials/like_button.html" with post=post is_liked=False total_likes=total_likes %}
                    {% endif %}
                </div>

                <div id="comment-section-{{ post.id }}" hx-swap="outerHTML">
                    {% include "partials/comment_button.html" with post=post comment_form=comment_form %}
                </div>
                <button class="btn btn-sm text-light p-2">
                    <i class="bi bi-arrow-repeat mr-1"></i> Repost
                </button>
            </div>


            {% for comment in post.get_all_comments %}
                <div class="comment-box">

                    <!-- Header -->
                    <div class="d-flex justify-content-between align-items-center mb-2">
                        <div class="d-flex align-items-center">
                            <img src="{{ comment.commented_by.profile.image.url }}" class="comment-avatar mr-2"
                                 alt="Profile">
                            <div>
                                <small class="comment-meta">@{{ comment.commented_by.username }}</small>
                            </div>
                        </div>
                        <!-- Dropdown -->
                        <div class="dropdown">
                            <button class="btn btn-sm btn-outline-light rounded-circle" data-toggle="dropdown">
                                <i class="bi bi-three-dots-vertical"></i>
                            </button>
                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-dark">
                                <button type="button" class="dropdown-item" data-toggle="modal"
                                        data-target="#updateCommentModal{{ comment.id }}">
                                    <i class="bi bi-pencil mr-2"></i> Update
                                </button>
                                <form method="POST" action="{% url 'blog-comment-delete' comment.id %}" class="m-0 p-0">
                                    {% csrf_token %}
                                    <button type="submit" class="dropdown-item text-danger">
                                        <i class="bi bi-trash mr-2"></i> Delete
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>

                    <!-- Content -->
                    <p class="mb-2">{{ comment.comment }}</p>

                    <!-- Reply section (if it's a reply to another comment) -->
                    {% if comment.get_all_replies %}
                        {% for reply in comment.get_all_replies %}
                            <div class="comment-thread mt-3">
                                <div class="d-flex align-items-center mb-1">
                                    <img src="{{ reply.replied_by.profile.image.url }}"
                                         class="comment-avatar mr-2" alt="Reply Profile">
                                    <div>
                                        <small class="comment-meta">@{{ reply.replied_by.username }}</small>
                                    </div>
                                </div>
                                <p>{{ reply.reply }}</p>
                            </div>
                        {% endfor %}
                    {% endif %}

                    <!-- Reply Button -->
                     <div id="comment-section-{{ comment.id }}" hx-swap="outerHTML">
                        {% include "partials/reply_button.html" with comment=comment reply_form=reply_form %}
                    </div>

                </div>

                <!-- Update Modal -->
                <div class="modal fade" id="updateCommentModal{{ comment.id }}" tabindex="-1" role="dialog"
                     aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content bg-dark text-light">
                            <div class="modal-header">
                                <h5 class="modal-title">Update Comment</h5>
                                <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
                                    <span>&times;</span>
                                </button>
                            </div>
                            <form method="POST" action="{% url 'blog-comment-update' comment.id %}">
                                {% csrf_token %}
                                <div class="modal-body">
                                    {{ comment_form|crispy }}
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-light rounded-pill">Save Changes</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock %}